### ISSUE TITLE
Startseite [Backend/Frontend]

### ISSUE THREAD

**Issue by marek-somm** [darafsa/fmi-lehrplanung#3]
Ein engeloggter User muss seine kommenden und vergangenen Veranstaltungen sehen können

- User im Frontend speichern [FE]

- Übersicht: Zukünftige Veranstaltungen
  - Vorschläge ausgegraut
  - Neu Angelegte anzeigen
- Neue Verasnt. aus alten erzeugen

**Comment by julien-klaus** [comment]
Ist der hier nicht schon komplett?

**Comment by julien-klaus** [comment]
Fertig
